name: carbon-lens-dev

services:
  app-postgres:
    image: postgres:13.22-alpine3.21
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: carbon_lens_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - app-pgsql-data:/var/lib/postgresql/data
    networks:
      - base-net

  api:
    image: ghcr.io/data354/carbon-lens-api:latest@sha256:3e984a7bd5083f71457b2512caad7924a2afcbef88040e6f6c25b8ade3feb761
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ../apps/api/.env
    volumes:
      - ../apps/api/secrets:/app/secrets:ro
    networks:
      - base-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      app-postgres:
        condition: service_healthy
    networks:
      - base-net

networks:
  base-net:
    driver: bridge

volumes:
  app-pgsql-data:
    driver: local
